-- AlterTable
ALTER TABLE "cars" ALTER COLUMN "updatedDt" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "order" ADD COLUMN     "createdBy" VARCHAR,
ADD COLUMN     "createdDt" TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN     "updatedBy" VARCHAR,
ADD COLUMN     "updatedDt" TIMESTAMP(3);

-- AlterTable
ALTER TABLE "users" ALTER COLUMN "createdDt" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "updatedDt" SET DATA TYPE TIMESTAMP(3);
